#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pack the inquiry relay into one file for the Cloudflare dashboard editor.

    python3 tools/pack_worker.py     -> worker/dist/worker.js

worker/index.js imports worker/lib.js; the dashboard editor takes a single
module, so this inlines lib.js above index.js (minus that import line).
Nothing else changes: the `cloudflare:email` import is a runtime module
the editor understands.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W = os.path.join(ROOT, "worker")


def main():
    lib = open(os.path.join(W, "lib.js"), encoding="utf-8").read()
    idx = open(os.path.join(W, "index.js"), encoding="utf-8").read()
    idx, n = re.subn(r'^import "\./lib\.js";\s*\n', "", idx, count=1, flags=re.M)
    if n != 1:
        raise SystemExit("index.js no longer imports ./lib.js the way pack_worker.py expects")
    out = ("/* GENERATED by tools/pack_worker.py from worker/lib.js + worker/index.js — "
           "edit those, not this. */\n\n" + lib + "\n\n" + idx)
    os.makedirs(os.path.join(W, "dist"), exist_ok=True)
    with open(os.path.join(W, "dist", "worker.js"), "w", encoding="utf-8") as f:
        f.write(out)
    print(f"  worker/dist/worker.js  {len(out.encode('utf-8')) // 1024} KB")


if __name__ == "__main__":
    main()
